### PR TITLE
Use relay style GUIDs 😌

### PR DESCRIPTION
**Pull request by declaneugeneleekennedy**
This PR returns ID fields as Relay global node IDs

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@declaneugeneleekennedy Merged 🎉 
In theory, `ID` should be opaque but who cares 😉

**Comment by IvanGoncharov** [comment]
On a second thought, it actually prevents conflicts where objects with different types have same IDs 👍

**Comment by declaneugeneleekennedy** [comment]
Thank you! Also thanks for this whole project, it's become an important part of our technology strategy.

**Comment by IvanGoncharov** [comment]
> Thank you! Also thanks for this whole project, it's become an important part of our technology strategy.

@declaneugeneleekennedy My pleasure. 
Now I'm curious about your use case. Can you please describe it, so I would know how to evolve this project. 
Also maybe you can write a blog post about your new strategy and how faker fit in it 😉

**Pull request merged**
