### PR TITLE
Upgrade Graphql-js version

### PR DESCRIPTION
**Pull request by amian84**
Hi @IvanGoncharov, I did a upgrade of graphql-js version and modify some code for work correclty.
With that, now the new description syntaxt are working but I don't know if all work propertly because for our propuse only need that   (#41 ).

Also i had to disable the lint into codemirror because with the update, if you define any type on the schema always show an error about the type definition, the error is becuase is not executable... Maybe you can fix that.

I do the pull-request only for if you would like start your migration to new version with this base.

Thanks for all

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@amian84 Thanks for PR 👍 
I have an urgent work so I will take a look next weekends.

**Comment by amian84** [comment]
I added more changes fixing when you extend another fake schema. If you try extend another faker schema, the buildSchema function failed because the system defines the faker schema more than once

**Comment by heiso** [comment]
Hey here ? Any news on this PR ?

**Comment by nilehmann** [comment]
What about now? Any news?

**Comment by arquio** [comment]
Any news? thanks

**Comment by amian84** [comment]
guys, while accept PR you can clone my repository and checkout to 'distFolder' branch, then you can execute 'sudo npm link' and with that your global graphql-faker binary will be my build with the changes.

**Comment by IvanGoncharov** [comment]
@amian84 Thanks a lot for PR 👍 
I used it as reference for migration, see recent commits.
I released `2.0.0-rc.1` 📦 that use the most recent `graphql` and `express-graphql`.
If you have time can you please test it?

**Pull request closed without merging**
