### PR TITLE
2017B CORS support added for easier configuration

### PR DESCRIPTION
**Pull request by ojczeo**
According to https://github.com/apollographql/apollo-client/issues/653

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@ojczeo Thank you.
Do you have any other problems or ideas for the faker?

I'm very interested to know how people use this tool.
> Added CORS for less integration problems with custom apps in development.

Do you use it to develop frontend app?
What client lib(Apollo, React) do you use?
You fake entire API or use extend mode to do add fields into existing objects?

**Comment by ojczeo** [comment]
@IvanGoncharov GraphQL faker is great tool! It very speeds up development of web apps with distributed services (if GraphQL api not working or is sitll in development).
I've used it as a fake api for my app, and it works very well.
One disadvantage - if mutations could return consistient data (based on mutation input) it would be incredible useful, or if it save mutation somewhere...
I'm using Apollo.

**Comment by IvanGoncharov** [comment]
> One disadvantage - if mutations could return consistient data (based on mutation input) it would be incredible useful, or if it save mutation somewhere...

@ojczeo I started to work on this and would try to commit today.
Just to be sure, do you mean something like this?
```
mutation {
  testMutation(input: {testStr: "Hello"}) {
    testStr
    anotherStr
  }
}
```
And result would be:
```
{
   "testStr": "Hello",
   "anotherStr": "string"
}
```
My assumption is that you are using Relay style mutation where data passed through single input object named "input". Is it correct?

**Comment by ojczeo** [comment]
@IvanGoncharov Yes, I've meant it exacly like that!
And yes, I'm using single input as mutation input.
It's very nice! Looking forward for update!

**Comment by IvanGoncharov** [comment]
@ojczeo I already pushed changes to the repo.
The only issue I see so far is aliases:
```
mutation {
  test(input:{testStr: "Hello"}) {
    testAlias: testStr
    anotherStr
  }
}
```
Produce:
```
{
  "test": {
    "testStr": "Hello",
    "anotherStr": "string"
  }
}
```
Not sure if there are other issues, so it would be great if you can test this changes before we publish a new version.

**Comment by IvanGoncharov** [comment]
@ojczeo I published new release with your changes and mutation trick 🎉

**Pull request merged**
