### PR TITLE
Add support for @sample directive

### LINKED ISSUE #12: Specify number of items in array
Would it be possible to add the ability to specify the number of items in a list?  I would imagine being able to enter a min number and max number then it returns a random number of items within that range.  If the numbers are the same then obviously it just returns that number.  An example of syntax is below but you might have a better idea.

image

### PR DESCRIPTION
**Pull request by MilosMosovsky**
In order to allow number of items which were hardcoded in `arrayResolver` I added `@sample` directive. (Naming taken from `lodash`/`underscore`)

Fixes #12

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@MilosMosovsky I think `sample` is very confusing in context of generate fake data.
\+ how would you handle two dimentional arrays (e.g. `[[Pet]]`)?

**Comment by dielduarte** [comment]
Hey! any news about this PR?

**Comment by ankithkonda** [comment]
Agreed, I believe this should be merged, the issue of X dimensional arrays can be solved in another PR. being able to specify a sample size on arrays is much needed

**Comment by skuteli** [comment]
Can you please merge?  
It's a feature that blocks me from using this **amazing** project as an essential component of quite a big setup.

**Comment by IvanGoncharov** [comment]
@MilosMosovsky Sorry it took so long.
I rebased your PR on top of `master`, changed the directive name to `@listLength` (since `@sample` is confusing name especially since we already have `@examples`) and added few minor changes.
Sadly I can't update this PR so I want ahead and committed 5db15f66f13c0c69f7d69b3be004ffd0ba455f05 keeping you as author.

@kristianmandrup @AntonioRedondo @dielduarte @ankithkonda @skuteli Just released `2.0.0-rc.10` 📦 with `@listLength` support. Can you please test it?

**Pull request closed without merging**
