### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by JamesKyburz**
This `PR` adds docker as an option to run.

The build will need to be setup using [dockerhub](https://hub.docker.com) (automated repository)

I would use the build settings with a github trigger (this presumes the use of git tags which `npm version` can create for us)

tag /^v[0-9.]+/ 
branch master latest

This would build latest on each published version along with a tagged version.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@JamesKyburz Merged 🎉 
Sorry for the delay, it was a pretty busy month for us.

**Comment by IvanGoncharov** [comment]
@JamesKyburz Thanks for instruction I setup build on dockerhub:
https://hub.docker.com/r/apisguru/graphql-faker/
And published new `1.5.1` version with matching tag:
https://github.com/APIs-guru/graphql-faker/tags
But I don't see it here:
https://hub.docker.com/r/apisguru/graphql-faker/tags/

Can you please help me to figure it out?

**Comment by romandragan** [comment]
@IvanGoncharov, I suppose, that your `1.5.1` tag just became `latest` on Docker Hub, cause it's only one, that exists in your repository. Once you'll publish new tag, it will appear on Docker Hub too.

**Comment by romandragan** [comment]
@IvanGoncharov, also don't forget to update Docker image name in README. Now it's wrong — `graphql-faker`, but must be full `apisguru/graphql-faker`.

**Comment by JamesKyburz** [comment]
@romandragan @IvanGoncharov Sorry but we haven't completed the automatic build on dockerhub yet. When we do I, we should be able to fix that in the next few days.

**Comment by JamesKyburz** [comment]
@IvanGoncharov Sorry I didn't get time to help :( I had a look on dockerhub and looks like you got it working?

**Comment by IvanGoncharov** [comment]
@JamesKyburz I suspect so. I would say DockeHub UI is very confusing:
image

If you have time, can you please test that `1.6.2` is correct build?

**Comment by JamesKyburz** [comment]
@IvanGoncharov I had a look and yes the v1.6.2 tagged image looks good :)

```sh
~ ᐅ docker run -ti --entrypoint=/bin/sh apisguru/graphql-faker:v1.6.2
/ #  cat /usr/local/lib/node_modules/graphql-faker/package.json  | grep version
  "version": "1.6.2"
~ ᐅ docker run -p 9002:9002  apisguru/graphql-faker:v1.6.2
```

**Pull request merged**
