### PR TITLE
More types and parameters support transferred from faker.js

### PR DESCRIPTION
**Pull request by slavik925**

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@slavik925 Thank you for PR 👍 
Would be great to merge it and add achieve full feature parity with `faker.js` however it's hard to imagine someone actually using `cityPrefix` (Port, North, ...) or `citySuffix` (burg, ton) and other simular ones. They are useful in Faker JS because you can use JS code to manipulate them, e.g. concatenate with other strings. 
So I don't want to add types to already huge list of types without real-life use-case to back it up.

That said I think it would be great to expose [faker.fake](https://github.com/Marak/faker.js#fakerfake) functionality:
```js
console.log(faker.fake("{{name.lastName}}, {{name.firstName}} {{name.suffix}}"));
// outputs: "Marks, Dean Sr."
```
In SDL it can look like this:
```graphql
type Query {
  formattedName: String @fakeString(pattern: "{{name.lastName}}, {{name.firstName}} {{name.suffix}}")
}
```
Do you want to work on such PR?

**Comment by slavik925** [comment]
1. Ok so I have removed the fields that possibly do not have any value for the real case use.
2. Yes for the next PR I could try to work on `@fakeString` feature. It would be good if you could add an additional notes what you exactly expect from this and some initial guidance where to start from. Thx!

**Comment by IvanGoncharov** [comment]
@slavik925 Merged 🎉 
I just added a few changes to your PR:
1. `format` option overlaps with `@fakeString` so I removed it and same goes for price`s `symbol`.
2. packed red/green/blue into `baseColor` object
3. explicitly marked skipped faker functions.

**Comment by IvanGoncharov** [comment]
> Yes for the next PR I could try to work on @fakeString feature. It would be good if you could add an additional notes what you exactly expect from this and some initial guidance where to start from. Thx!

@slavik925 I just remember that in addition to `faker.fake` I also wanted to incorporate [randexp.js](https://github.com/fent/randexp.js) and I'm sure how to add them both. Need to think more about it 🤔

**Pull request merged**
