### PR TITLE
Adds support for CORS options to be passed in

### PR DESCRIPTION
**Pull request by securingsincity**

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
Hi @securingsincity,

Can you please describe use case?
It looks like CORS middleware provides very reasonable default:
https://github.com/expressjs/cors/blob/master/lib/index.js#L8-L13

**Comment by securingsincity** [comment]
@IvanGoncharov The use case is if you are trying to include credentials from the client. Which requires that the origin be defined and the credentials policy to be defined. 

For example sending a request from `foo:8080` to `localhost:9002` with a cookie included needs an origin other than `*` and credentials to `true`

**Comment by IvanGoncharov** [comment]
@securingsincity Got it, thank you for explanation.
Can you set `Access-Control-Allow-Credentials` every time `--cors-origin` specified?
This way we will have one option instead of two.

**Comment by securingsincity** [comment]
I think that works much better @IvanGoncharov. Feel free to review again.

**Comment by IvanGoncharov** [comment]
@securingsincity Thank you 👍 
Do you have any other problems or ideas for the faker?
BTW. Do you use it to fake entire API or to extend existing one with fake fields?

**Comment by securingsincity** [comment]
I just started using it the other day but it was to extend. As I was using it I realized I probably want to fake the entire thing so I will probably play with that over the weekend. I really enjoy it, the UI to edit the .graphql file is a really nice touch. I'll let you know if i think of anything it needs

**Comment by IvanGoncharov** [comment]
@securingsincity I publish new release with your changes 🎉

**Comment by securingsincity** [comment]
@IvanGoncharov awesome thanks!

**Pull request merged**
