### PR TITLE
signal handling in docker

### PR DESCRIPTION
**Pull request by JamesKyburz**
Handle signals correctly when running in docker, making stop / restart much quicker.

Before change

ᐅ time docker-compose stop graphql-repl
Stopping graphql-repl_1 ... done
docker-compose stop graphql-repl  1.16s user 0.26s system 11% cpu 12.056 total

After change

ᐅ time docker-compose stop graphql-repl
docker-compose stop graphql-repl  0.60s user 0.11s system 92% cpu 0.757 total

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@JamesKyburz Merged 🎉 
Thank you for PR 👍 

BTW. I didn't have an opportunity to use Docker in my projects but I see how it can be useful for other people. So if you have separate Docker file for running Faker it would be great to include it as part of the repo.

**Comment by JamesKyburz** [comment]
@IvanGoncharov Thanks. I can send a `PR` with a `Dockerfile` including all the env options.

I could also include in the `PR` how we could setup an automated build on dockerhub for each release? I do this for [level-eventstore](https://hub.docker.com/r/jameskyburz/level-eventstore/)

**Comment by IvanGoncharov** [comment]
>  I can send a PR with a Dockerfile including all the env options.

@JamesKyburz  That would be great 🎊 

> I could also include in the PR how we could setup an automated build on dockerhub for each release?

I'm docker-illiterate at the moment 😞
Do you plan to add some script to automatically deploy docker images?

**Comment by JamesKyburz** [comment]
@IvanGoncharov  :) Yes the plan is for [dockerhub](https://dockerhub.com) to create a new docker image on every release.

Would it be ok to git tag future releases? `npm version` does this for us.

**Comment by IvanGoncharov** [comment]
> Would it be ok to git tag future releases?

@JamesKyburz Yes, definitely. Plus having tags is good on its own.

**Pull request merged**
