### PR TITLE
Upgrade and fix windows issues

### PR DESCRIPTION
**Pull request by zephraph**
## WIP: DO NOT MERGE

My intent was to implement the suggestion in #13, but I couldn't even get the project to run correctly on windows. It wasn't the fault of the project itself, just weird graphql dependency issues. I started trying to solve those and... well... just went a little overboard. 

All the dependencies are up-to-date. I moved off of all forked libraries. I switched over to apollo's express.js graphql implementation, being that they give the baseline of what `graphql-express` has, then some. 

With all that being said, **it's currently broken.**

image

My next steps are adding tests, determining the scope and cause of the current breakages, fixing everything, and getting it into a semi-presentable state. 

Any help will be appreciated.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@zephraph Thank you for help. I wasn't aware that Faker is broken on Windows :(
It would be great if you help us to fix it.

However we can't make Faker work with vanilla `graphql-js` untill https://github.com/graphql/graphql-js/pull/746 is merged.Same story with `express-graphql`. It depends on `graphql-js` and it will not work with conflicting version. Switching to `graphql-server-express` also won't help either, since you will have exactly same problem.
So dependency on forks is **intentional**. 

Do you have issues with running Faker on Windows?
Good start would be to split your Windows related changes into separate PR.

**Comment by zephraph** [comment]
I knew the forks were intentional, I just didn't know the exact issue. Thanks for the info. 

I did have trouble running on Windows, yeah. It kept throwing an invariant error saying the schema must be valid and there should only be one version of graphql in node_modules. That was with the example schema that you provide when it starts. Works fine on OSX though. 

The other thing was the reliance of some shell cmds that aren't consistently available on Windows. I'll pair things down a bit.

I would say there's a huge need for tests though.

**Comment by IvanGoncharov** [comment]
> It kept throwing an invariant error saying the schema must be valid and there should only be one version of graphql in node_modules.

Try to install faker into empty folder:
```sh
npm init
npm install graphql-faker
npm run graphql-faker
./node_modules/.bin/graphql-faker
```
If it helps that mean you have conflicting `graphql` package in global `node_modules`.
In any case please write about the result here.

**Comment by zephraph** [comment]
Sorry, this dropped off my radar. I've been a bit busy lately. I'm going to close this PR as it's not really useful in its current state.

**Comment by IvanGoncharov** [comment]
@zephraph No problem. You always welcome to open new PRs or issues.

**Pull request closed without merging**
