### PR TITLE
Split index.ts to index.ts/cli.ts

### PR DESCRIPTION
**Pull request by liuchong**
## commit logs

1. It's intend to use faker in express conveniently, such as:

``` javascript
const { applyFaker } = require('graphql-faker')
const express = require('express')
const app = express()
// your codes here
applyFaker(app, { fileArg: '/path/to/schema.graphql' })
// more codes
```

2. Use cli.js as bin

## next step

Maybe should add a method to directly pass string as schema to faker server, so we could simple pass generated schema string to it.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@liuchong Wow 😮 Pretty big change
Can you please describe your use case?
Do you need the editor as part of `applyFaker` or you just want embedded mock API into your server?

**Comment by liuchong** [comment]
https://gist.github.com/54189161ccbc630ffc09f033fabad0a4
https://gist.github.com/88187eb51dbb4baa5084eb6f3874b55b

I've created two simple scripts based my webpack setup.
Too connect to backend from my frontend, I want use the same port on my develop machine, so I've created a proxy on express, forwards the requests to ":3000/graphql" to graphql-faker's 9002 port.

So I was just think about what, if I could just require the graphql-faker library and then apply it onto my own express instance, the procedure should become much more simple, also released another port.

Also, I have my graphql schema in a ts file just like:
``` typescript
export default typeDefs = `
...
`
```
(It is to avoid the trouble of include .graphql files into tsc results)
I could generate schema with my .ts schema and then pass the schema file to faker server, OR, I could just pass the generated string :joy_cat:

**Comment by liuchong** [comment]
@IvanGoncharov 
In fact, just the mock API should be ok for now

**Comment by IvanGoncharov** [comment]
@liuchong Thanks for detail explanation 👍 
Maybe following suggestions will solve issues you are facing.

> Too connect to backend from my frontend, I want use the same port on my develop machine, so I've created a proxy on express, forwards the requests to ":3000/graphql" to graphql-faker's 9002 port.

You can pass `-p 3000`  argument or define `PORT` environment variable.

>(It is to avoid the trouble of include .graphql files into tsc results)

IMHO it's better to keep schema in `.graphql` since there are other tools (including some IDEs) which also consume `.graphql` files.
So if you are using webpack for your application I can recommend using [raw-loader](https://github.com/webpack-contrib/raw-loader).

**Comment by liuchong** [comment]
Thanks, and I am have using the -p argument in my script, but if use 3000, my server.js script cannot use it, isn't it?

I'm just started at front-end development so maybe using some method not so idiomatically. It is been splited into server/client sub projects, and I didn't use webpack in server side. The client side sub-proj has an own server.js.

Uhh...I just realized I could just treat graphql-faker as my server side for now :joy_cat:

**Comment by liuchong** [comment]
Maybe I could close it for now, but if there is a way to require graphql-faker to treat as a library, we could do more programmatic things on it.

**Comment by IvanGoncharov** [comment]
@liuchong I also thought about exposing `graphql-faker` as a library.
But I think public APIs should represent some abstraction. Ideally, it would expose two functions (fakeSchema and fakeSchemaExtension) which return `GraphQLSchema` object that you can plug in `express-graphql`, `apollo-server` or any other tool which support schema objects.

**Comment by liuchong** [comment]
@IvanGoncharov Thanks for the (fakeSchema and fakeSchemaExtension) :100:

**Pull request closed without merging**
