### PR TITLE
Forward headers

### PR DESCRIPTION
**Pull request by JamesKyburz**
Forwarding headers to extended url to give the query user context.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@JamesKyburz Thank you for PR 👍 
Looks great, the only issue I have is that passing all headers by default can cause a lot of issues.
How about `--forward-headers` argument?
Can you please try  https://github.com/APIs-guru/graphql-faker/commit/45c8c384e27fae6db1cf505410b674f6a2028d4c where I implemented this option on top of your PR?

**Comment by JamesKyburz** [comment]
@IvanGoncharov Thanks. Agreed that it's better to specify what is forwarded.

I verified that your change works :)

**Comment by JamesKyburz** [comment]
@IvanGoncharov Unfortunately the cli now doesn't work without extend and forward-headers

get error
```sh
Implications failed:
  forward-headers -> extend
```
I will have a look at the `yargs` stuff :)

**Comment by JamesKyburz** [comment]
removed default [], now it works.

**Comment by IvanGoncharov** [comment]
@JamesKyburz Merged 🎉 
Will release new version (`1.4.0`) after #24 will be merged.

**Comment by JamesKyburz** [comment]
@IvanGoncharov Great thanks.

**Comment by IvanGoncharov** [comment]
@JamesKyburz BTW. I will be on [NordicsAPI Summit](https://nordicapis.com/events/the-2017-api-platform-summit) in Stockholm. Would be great to chat about GraphQL if you also coming 😄

**Comment by JamesKyburz** [comment]
@IvanGoncharov I don't know if I can make it yet, but would be great to meet and chat about GraphQL!

**Pull request merged**
