### PR TITLE
Change 'random' to 'datatype' to fix deprecations in faker

### LINKED ISSUE #148: Fix deprecation Warning: faker.random
Some of the methods of `faker.random` are now deprecated like `number` or `uuid`. They are now located under `faker.datatype`:

> Deprecation Warning: faker.random.number is now located in faker.datatype.number

### PR DESCRIPTION
**Pull request by Robvio**
Fixes #148

### CODE REVIEW

**Comment by fogelfish** [comment]
Can you me the status of this fix?  I'm using graphql-faker@2.0.0-rc.24 and I see these deprecation messages repeating in the terminal.  Thank you.

```
Deprecation Warning: faker.random.number is now located in faker.datatype.number
Deprecation Warning: faker.random.uuid is now located in faker.datatype.uuid
```

**Comment by IvanGoncharov** [comment]
@Robvio Thanks a lot 👍 
Sorry for the late merge.

**Comment by IvanGoncharov** [comment]
@Robvio @fogelfish Merged and released as `v2.0.0-rc.25`

**Comment by fogelfish** [comment]
`Deprecation Warning: faker.random.uuid is now located in faker.datatype.uuid`

...repeating in the terminal using the newest release:

**$ graphql-faker --version**
`2.0.0-rc.25`

**Comment by sneko** [comment]
@IvanGoncharov same as for @fogelfish .

Being spammed by:
```
Deprecation Warning: faker.random.uuid is now located in faker.datatype.uuid
Deprecation Warning: faker.random.uuid is now located in faker.datatype.uuid
Deprecation Warning: faker.random.uuid is now located in faker.datatype.uuid
Deprecation Warning: faker.random.uuid is now located in faker.datatype.uuid
```
even with `2.0.0-rc.25` 🤔

**Pull request merged**
