### PR TITLE
add new @fake function: unplashUrl

### PR DESCRIPTION
**Pull request by Kageetai**

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@Kageetai Thanks for PR 👍 
It looks like `faker.js` natively support unsplash we just need to use it instead of current provider:
https://github.com/Marak/faker.js/blob/acfbf3becde772adf4f6bf63bb1897a37ebddd3a/lib/image_providers/unsplash.js
Can you please test it and switch the existing `imageUrl` to it?

**Comment by Kageetai** [comment]
@IvanGoncharov Yes, I saw that, but it doesn't seem to be usable yet: `faker.image.unsplash` or so does not work, although it looks like it should according this line: https://github.com/Marak/faker.js/blob/acfbf3becde772adf4f6bf63bb1897a37ebddd3a/lib/image.js#L220
Something about how this is bound here: https://github.com/Marak/faker.js/blob/acfbf3becde772adf4f6bf63bb1897a37ebddd3a/lib/index.js#L76
I didn't wanna investigate too much, also faker does not seem to respond to PRs that much, so I created this PR, also so I can already test it in our project

**Comment by IvanGoncharov** [comment]
I switched `imageUrl` to unsplash in 682affd21b1d86cadd6d096b32ab6fe971503067

**Comment by Kageetai** [comment]
Nice, will you also publish this to NPM soon?

**Comment by IvanGoncharov** [comment]
@Kageetai Released as `graphql-faker@2.0.0-rc.18` 🎉

**Comment by Kageetai** [comment]
Awesome, thanks a lot!

**Pull request closed without merging**
